// <auto-generated />
using System;
using CrossChat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrossChat.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260513100210_TelegramUserBot")]
    partial class TelegramUserBot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrossChat.Data.Entities.BlueSkySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("Did")
                        .HasColumnType("text");

                    b.Property<string>("Handle")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PdsUrl")
                        .HasColumnType("text");

                    b.Property<string>("PrivateKeyJson")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BlueSkySettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.BotResponseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TokensSpent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("BotResponseLogs");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.FacebookSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PageAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .HasColumnType("text");

                    b.Property<string>("PageName")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FacebookSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramBotCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomPrompt")
                        .HasColumnType("text");

                    b.Property<string>("InstagramSenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InstagramSettingsId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InstagramSettingsId");

                    b.ToTable("InstagramBotCustomers");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("AllowedReactions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramBusinessId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCommentsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDirectEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReactionsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAnswerMessagesCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAnswersTokensCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ProcessAudios")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProcessPhotos")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProcessVideos")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InstagramSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.TelegramSettings", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("BotToken")
                        .HasColumnType("text");

                    b.Property<string>("BotUsername")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("TelegramSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.TelegramUserBotSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DcId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProxyHost")
                        .HasColumnType("text");

                    b.Property<string>("ProxyPass")
                        .HasColumnType("text");

                    b.Property<int?>("ProxyPort")
                        .HasColumnType("integer");

                    b.Property<string>("ProxyUser")
                        .HasColumnType("text");

                    b.Property<byte[]>("SessionData")
                        .HasColumnType("bytea");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TgUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TelegramUsersBotSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.ThreadsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreadsUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThreadsSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.XSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("ScreenName")
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("XUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("XSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.BlueSkySettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany("BlueSkySettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.BotResponseLog", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.InstagramBotCustomer", "Customer")
                        .WithMany("ResponseLogs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.FacebookSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany("FacebookSettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramBotCustomer", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.InstagramSettings", "InstagramSettings")
                        .WithMany("Customers")
                        .HasForeignKey("InstagramSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstagramSettings");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany("InstagramSettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.TelegramSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithOne("TelegramSettings")
                        .HasForeignKey("CrossChat.Data.Entities.TelegramSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.TelegramUserBotSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.ThreadsSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany("ThreadsSettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.XSettings", b =>
                {
                    b.HasOne("CrossChat.Data.Entities.User", "User")
                        .WithMany("XSettingsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramBotCustomer", b =>
                {
                    b.Navigation("ResponseLogs");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.InstagramSettings", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("CrossChat.Data.Entities.User", b =>
                {
                    b.Navigation("BlueSkySettingsList");

                    b.Navigation("FacebookSettingsList");

                    b.Navigation("InstagramSettingsList");

                    b.Navigation("TelegramSettings");

                    b.Navigation("ThreadsSettingsList");

                    b.Navigation("XSettingsList");
                });
#pragma warning restore 612, 618
        }
    }
}
